### ISSUE TITLE
Undefined Cucumber Scenarios

### ISSUE THREAD

**Issue by ltseng1** [mlee138/shift-swapper#1]
Cucumber scenarios for what users see within login/registration page UI outputs one scenario passing with two scenarios undefined.

I'd imagine that the "Then I should see" step just simply needs to be implemented in the home_steps.rb, however for some particular reason "When I follow" is not being recognized despite having a block written for it.

![image](https://user-images.githubusercontent.com/24739867/54939654-7d75a600-4eff-11e9-9b19-51af43864c86.png)

**Comment by stedebun** [comment]
Also working on this but due to the user limit of github I am not listed in the assignee's.
